### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by 9sanha** [Munaso/Node.lv1#1]
첫 express 과제 고생하셨습니다!

## routes.post.js

Validation은 데이터베이스와의 비정상적인 통신과 FrontEnd - Backend 통신에 비정상적인 값으로 하여금 
예기치 못한 로직이 수행되는 것을 미연에 방지할 수 있습니다!

작성해주신 postSchema에서는 대부분의 항목이 `{ required : true }`로 설정되어 있었으나,
해당 게시글 생성 그에 대한 검증 로직이 없어 오류를 발생시킬 수 있습니다.

``` javascript
    if (typeof title !== 'string' || title === '') 
      return res.status(400).json({ 'message' : '비정상적인 요청입니다' })
   ...
```

## 전체 게시글 목록 조회

정렬은 DB에서도 가능해요!
정렬을 현재는 Posts.find({}) 를 통하여 게시글을 배열로 조회한 뒤
.sort() 를 통해 정렬하고 있습니다!
**DB에서** 정렬된 결과물을 가져오는 방법도 있습니다.
| ex. Posts.find({}).sort({ createdAt: 1 })

## 게시글 수정

게시글 수정은 Document를 통해서 가능해요!
mongoose 는 ODM (Object Document Mapping)이기 때문에 실제 update SQL 없이 내부적으로 값 변경 후 저장시킬 수  있습니다.

``` javascript
   const post = await Posts.findOne({ postId: postId, password: password })
   if (!post) return res.status(400).json({ message: '패스워드와 수정내용을 확인해주세요' })
  
  post.title = title
  post.content = content
  await post.save()

  return res.status(200).json({ message: '게시글을 수정하였습니다.' })
```

**Comment by Munaso** [comment]
감사합니다. 반영하여 수정했습니다.
